name: Is It Snappy?
description: Measure input-to-output latency with your iPhone
author: Chad Austin
title: Is It Snappy?
theme: jekyll-theme-cayman
markdown: kramdown
google_analytics: UA-96650815-1
include: ['_pages']
